name: Wheels

on:
  workflow_dispatch:


jobs:

  build_wheels:
    name: Build wheel
    runs-on: ubuntu-24.04-arm  # macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        run: apt update && apt install -y wget cmake ninja-build g++ libx11-dev

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download vtk
        run: wget https://www.vtk.org/files/release/9.4/VTK-9.4.1.tar.gz

      - name: Extract vtk
        run: tar -xzf VTK-9.4.1.tar.gz

      - name: Build vtk
        run: |
            cd VTK-9.4.1
            cmake -GNinja -DVTK_WHEEL_BUILD=ON -DVTK_WRAP_PYTHON=ON -DCMAKE_BUILD_TYPE=Release -DVTK_GROUP_ENABLE_Web=WANT -S . -B build
            cmake --build build
            cd build && python3 setup.py bdist_wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: VTK-9.4.1/build/dist/*.whl
